In [5]:
import numpy as np
import random

import matplotlib.pyplot as plt
from model.tools.OneHotEncoderTools import OneHotEncoderTools

In [2]:
data = np.genfromtxt("datasets/train_mnist.csv", delimiter=",")
print('reed')


reed


In [3]:
#mytest
data_shuffle = data.copy()
data_shuffle = data_shuffle[1:]
print(data_shuffle, data_shuffle.shape)

[[1. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [1. 0. 0. ... 0. 0. 0.]
 ...
 [7. 0. 0. ... 0. 0. 0.]
 [6. 0. 0. ... 0. 0. 0.]
 [9. 0. 0. ... 0. 0. 0.]] (42000, 785)


In [7]:
#mytest
# data_shuffle = np.array([1,2,3,4,5])
# np.random.shuffle(data_shuffle)
# print(data_shuffle, type(data_shuffle))


# print(type(data_shuffle))
np.random.shuffle(data_shuffle)
data_shuffle = data_shuffle[:3000]
# print(data_shuffle[0])
matrix_dataset_3d = []
matrix_dataset_3d_y = []
for row in data_shuffle:
    # print(row[0])
    matrix = np.array(row[1:]).reshape((28,28, 1))/255
    encode_data = OneHotEncoderTools.to_full(int(row[0]), 10)
    matrix_dataset_3d.append(matrix)
    matrix_dataset_3d_y.append(encode_data)

In [8]:
#mytest
# random.shuffle(matrix_dataset_3d)
cut_3d_x = np.array(matrix_dataset_3d)
cut_3d_y = np.array(matrix_dataset_3d_y)
print(cut_3d_y.shape)

(3000, 10)


In [9]:
from keras import models
from keras import layers
import keras

model = models.Sequential()
model.add(layers.Conv2D(1, (3, 3), activation='linear', input_shape=(28, 28, 1)))
model.add(layers.Flatten())
model.add(layers.Dense(100, activation='relu'))
# model.add(layers.Dense(20, activation='sigmoid'))
model.add(layers.Dense(10, activation='softmax'))
model.compile(optimizer=keras.optimizers.Adam(learning_rate=0.0005), loss='categorical_crossentropy', metrics=['accuracy'])


In [10]:
model.fit(cut_3d_x, cut_3d_y, epochs=10, batch_size=1)

Epoch 1/10


3000/3000 [==============================] - 6s 2ms/step - loss: 0.5431 - accuracy: 0.8340
Epoch 2/10
3000/3000 [==============================] - 4s 1ms/step - loss: 0.2476 - accuracy: 0.9307
Epoch 3/10
3000/3000 [==============================] - 4s 1ms/step - loss: 0.1618 - accuracy: 0.9473
Epoch 4/10
3000/3000 [==============================] - 4s 1ms/step - loss: 0.1103 - accuracy: 0.9640
Epoch 5/10
3000/3000 [==============================] - 4s 1ms/step - loss: 0.0797 - accuracy: 0.9750
Epoch 6/10
3000/3000 [==============================] - 4s 1ms/step - loss: 0.0596 - accuracy: 0.9797
Epoch 7/10
3000/3000 [==============================] - 5s 2ms/step - loss: 0.0453 - accuracy: 0.9833
Epoch 8/10
3000/3000 [==============================] - 5s 2ms/step - loss: 0.0399 - accuracy: 0.9867
Epoch 9/10
3000/3000 [==============================] - 4s 1ms/step - loss: 0.0341 - accuracy: 0.9883
Epoch 10/10
3000/3000 [==============================] - 5s 2ms/step - loss: 0.0

In [14]:
model.summary()

Model: "sequential"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 conv2d (Conv2D)             (None, 26, 26, 1)         10        
                                                                 
 flatten (Flatten)           (None, 676)               0         
                                                                 
 dense (Dense)               (None, 100)               67700     
                                                                 
 dense_1 (Dense)             (None, 10)                1010      
                                                                 
Total params: 68720 (268.44 KB)
Trainable params: 68720 (268.44 KB)
Non-trainable params: 0 (0.00 Byte)
_________________________________________________________________


In [12]:
import tf2onnx

In [13]:
import tensorflow as tf
from tf2onnx import convert

# Загрузка модели Keras
keras_model = model  # ваша модель Keras

# Преобразование модели Keras в ONNX
onnx_model, _ = convert.from_keras(keras_model)

# Сохранение модели ONNX в файл
onnx_file_path = "saved_models/model1.onnx"
tf.io.write_graph(onnx_model, ".", onnx_file_path, as_text=False)

'.\\saved_models/model1.onnx'

In [15]:
onnx_model

ir_version: 8
producer_name: "tf2onnx"
producer_version: "1.16.1 15c810"
graph {
  node {
    input: "conv2d_input"
    input: "new_shape__12"
    output: "sequential/conv2d/BiasAdd__6:0"
    name: "sequential/conv2d/BiasAdd__6"
    op_type: "Reshape"
    domain: ""
  }
  node {
    input: "sequential/conv2d/BiasAdd__6:0"
    input: "sequential/conv2d/Conv2D/ReadVariableOp:0"
    input: "sequential/conv2d/BiasAdd/ReadVariableOp:0"
    output: "sequential/conv2d/BiasAdd:0"
    name: "sequential/conv2d/BiasAdd"
    op_type: "Conv"
    attribute {
      name: "dilations"
      ints: 1
      ints: 1
      type: INTS
    }
    attribute {
      name: "strides"
      ints: 1
      ints: 1
      type: INTS
    }
    attribute {
      name: "kernel_shape"
      ints: 3
      ints: 3
      type: INTS
    }
    attribute {
      name: "group"
      i: 1
      type: INT
    }
    domain: ""
  }
  node {
    input: "sequential/conv2d/BiasAdd:0"
    input: "const_fold_opt__13"
    output: "sequenti