In [1]:
import keras.utils
import numpy as np

In [4]:
keras.utils.to_categorical([[3],[2],[3],[5],[10]])

array([[0., 0., 0., 1., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 1.]], dtype=float32)

In [20]:
cat = keras.utils.to_categorical([[0, 1], [2, 2]])
print(cat)
print(len(cat))

[[[1. 0. 0.]
  [0. 1. 0.]]

 [[0. 0. 1.]
  [0. 0. 1.]]]
2


In [45]:
float_array = [.1, 1.1123, 3.043]
float_array = [[0, 1], [2, 2]]
print(keras.utils.to_categorical(float_array))
int_array = np.array(float_array, dtype='int64')
print(int_array)
shape = int_array.shape
print(np.zeros(shape))

[[[1. 0. 0.]
  [0. 1. 0.]]

 [[0. 0. 1.]
  [0. 0. 1.]]]
[[0 1]
 [2 2]]
[[0. 0.]
 [0. 0.]]


In [21]:
a = np.array([1, 2, 3], ndmin=2, dtype='float32')
print(a)
print(len(a[0]))

[[1. 2. 3.]]
3


In [46]:
y = np.zeros((2, 3, 4))
print(y)
# y.shape = (3, 8)
print(y.shape)
# y.shape = (3, 16)
# y

[[[0. 0. 0. 0.]
  [0. 0. 0. 0.]
  [0. 0. 0. 0.]]

 [[0. 0. 0. 0.]
  [0. 0. 0. 0.]
  [0. 0. 0. 0.]]]
(2, 3, 4)


In [88]:
def to_categorical(x, num_classes=None):
    x = np.array(x, dtype="int64")
    print(x)
    input_shape = x.shape
    print(input_shape)
    # Shrink the last dimension if the shape is (..., 1).
    if input_shape and input_shape[-1] == 1 and len(input_shape) > 1:
        print('ye')
        input_shape = tuple(input_shape[:-1])

    x = x.reshape(-1)
    print(x)
    if not num_classes:
        num_classes = np.max(x) + 1
    batch_size = x.shape[0]
    print(f'batch {batch_size}\nnum_classes {num_classes}')
    categorical = np.zeros((batch_size, num_classes))
    print(categorical)
    categorical[np.arange(batch_size), x] = 1
    print(categorical[np.arange(batch_size), x])
    print(categorical)
    output_shape = input_shape + (num_classes,)
    print(f'out {output_shape}')
    categorical = np.reshape(categorical, output_shape)
    print(categorical)
    return categorical

# to_categorical([[1, 2], [2, 2], [3, 2]])
to_categorical([[1], [2], [4]])
# to_categorical([1, 2, 3])

[[1]
 [2]
 [4]]
(3, 1)
ye
[1 2 4]
batch 3
num_classes 5
[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]
[1. 1. 1.]
[[0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 0. 1.]]
out (3, 5)
[[0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 0. 1.]]


array([[0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 1.]])

In [50]:
to_categorical([1, 2, 3])

[1 2 3]
(3,)


array([[0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])